using BossGearSynthesis.Analysis;
using BossGearSynthesis.BossDetection;
using BossGearSynthesis.Defaults;
using BossGearSynthesis.Enchantments;
using BossGearSynthesis.Gear;
using BossGearSynthesis.Logging;
using BossGearSynthesis.Outfit;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace BossGearSynthesis;

public class Program
{
    private static Lazy<Settings.Settings> _settings = null!;

    public static async Task<int> Main(string[] args)
    {
        return await SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings(
                nickname: "Settings",
                path: "settings.json",
                out _settings)
            .SetTypicalOpen(GameRelease.SkyrimSE, "BossGearSynthesis.esp")
            .Run(args);
    }

    public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        var settings = _settings.Value;
        SettingsDefaults.Apply(settings);

        var selector = new BossSelector(state, settings);
        var classifier = new TierClassifier(settings);
        var analyzer = new StrengthAnalyzer(settings, classifier);
        var effectMap = new EffectMap(settings.EffectMap);
        var enchBuilder = new EnchantmentBuilder(settings, effectMap);
        var slotResolver = new SlotResolver(settings);
        var matcher = new MaterialMatcher(settings);
        var itemBuilder = new ItemBuilder(settings);
        var outfitPatcher = new OutfitPatcher();
        var report = new DryRunReport();

        foreach (var boss in selector.Select())
        {
            var isUnique = selector.IsNamedUnique(boss);
            var profile = analyzer.Analyze(boss, isUnique, state);
            if (profile is null) { report.Skipped(boss, "no skills resolved"); continue; }

            var pick = slotResolver.PickSlot(boss, state);
            if (pick is null) { report.Skipped(boss, "no eligible outfit slot"); continue; }

            var baseArmor = matcher.Choose(pick.Item, pick.Slot, state);
            var primaryMag = MagnitudeFormula.ComputePrimary(profile, settings.MagnitudeScaling);
            var resolvedPick = pick with { Item = baseArmor };

            if (settings.Output.DryRun)
            {
                report.Patched(boss, profile, resolvedPick, primaryMag);
                continue;
            }

            var ench = enchBuilder.Build(state, boss, profile, Suffix(boss));
            if (ench is null) { report.Skipped(boss, "no MGEF for top combat skill"); continue; }

            var item = itemBuilder.Build(state, boss, baseArmor, ench, profile, primaryMag);
            outfitPatcher.Apply(state, boss, resolvedPick, item);
            report.Patched(boss, profile, resolvedPick, primaryMag);

            if (settings.Output.VerboseLog)
                Console.WriteLine($"[BossGear] {boss.Name?.String ?? boss.EditorID} -> {profile.TopCombatSkill} {primaryMag:F1}");
        }

        var reportPath = Path.Combine(state.DataFolderPath, settings.Output.ReportFileName);
        try { report.Write(reportPath); } catch { /* best effort */ }
    }

    private static string Suffix(INpcGetter npc) =>
        (npc.EditorID ?? npc.FormKey.ID.ToString("X8")).Replace(" ", "_");
}
