using BossGearSynthesis.Analysis;
using BossGearSynthesis.BossDetection;
using BossGearSynthesis.Defaults;
using BossGearSynthesis.Enchantments;
using BossGearSynthesis.Gear;
using BossGearSynthesis.Logging;
using BossGearSynthesis.Outfit;
using BossGearSynthesis.Settings;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace BossGearSynthesis;

public class Program
{
    private static Lazy<Settings.Settings> _settings = null!;

    public static async Task<int> Main(string[] args)
    {
        return await SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings(
                nickname: "Settings",
                path: "settings.json",
                out _settings)
            .SetTypicalOpen(GameRelease.SkyrimSE, "BossGearSynthesis.esp")
            .Run(args);
    }

    public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        var settings = _settings.Value;
        SeedDefaults(settings);

        var selector = new BossSelector(state, settings);
        var classifier = new TierClassifier(settings);
        var analyzer = new StrengthAnalyzer(settings, classifier);
        var effectMap = new EffectMap(settings.EffectMap);
        var enchBuilder = new EnchantmentBuilder(settings, effectMap);
        var slotResolver = new SlotResolver(settings);
        var matcher = new MaterialMatcher(settings);
        var itemBuilder = new ItemBuilder(settings);
        var outfitPatcher = new OutfitPatcher();
        var report = new DryRunReport();

        foreach (var boss in selector.Select())
        {
            var isUnique = selector.IsNamedUnique(boss);
            var profile = analyzer.Analyze(boss, isUnique, state);
            if (profile is null) { report.Skipped(boss, "no skills resolved"); continue; }

            var pick = slotResolver.PickSlot(boss, state);
            if (pick is null)
            {
                if (TryJewelryFallback(state, settings, boss, profile,
                        enchBuilder, itemBuilder, outfitPatcher, report))
                    continue;

                report.Skipped(boss, "no eligible outfit slot");
                continue;
            }

            var baseArmor = matcher.Choose(pick.Item, pick.Slot, state);
            var primaryMag = MagnitudeFormula.ComputePrimary(profile, settings.MagnitudeScaling);

            if (settings.Output.DryRun)
            {
                report.Patched(boss, profile, pick with { Item = baseArmor }, primaryMag);
                continue;
            }

            var ench = enchBuilder.Build(state, boss, profile, Suffix(boss));
            if (ench is null) { report.Skipped(boss, "no MGEF for top combat skill"); continue; }

            var item = itemBuilder.Build(state, boss, baseArmor, ench, profile, primaryMag);
            outfitPatcher.Apply(state, boss, pick with { Item = baseArmor }, item);
            report.Patched(boss, profile, pick with { Item = baseArmor }, primaryMag);

            if (settings.Output.VerboseLog)
                Console.WriteLine($"[BossGear] {boss.Name?.String ?? boss.EditorID} -> {profile.TopCombatSkill} {primaryMag:F1}");
        }

        var reportPath = Path.Combine(state.DataFolderPath, settings.Output.ReportFileName);
        try { report.Write(reportPath); } catch { /* best effort */ }
    }

    private static void SeedDefaults(Settings.Settings settings)
    {
        if (settings.EffectMap.SkillEffects.Count == 0)
            settings.EffectMap.SkillEffects = EffectMapDefaults.BuildSkillDefaults();
        if (settings.EffectMap.AttributeEffects.Count == 0)
            settings.EffectMap.AttributeEffects = EffectMapDefaults.BuildAttributeDefaults();

        if (settings.BossDetection.NamedUniqueAllowlist.Count == 0)
            foreach (var fk in NamedUniqueAllowlist.FormKeys)
                settings.BossDetection.NamedUniqueAllowlist.Add(new FormLink<INpcGetter>(fk));

        if (settings.AhzidalSpecial.Ahzidal.IsNull)
            settings.AhzidalSpecial.Ahzidal = new FormLink<INpcGetter>(NamedUniqueAllowlist.Ahzidal);
        if (settings.AhzidalSpecial.ExtraEffectMgef.IsNull)
            settings.AhzidalSpecial.ExtraEffectMgef = new FormLink<IMagicEffectGetter>(NamedUniqueAllowlist.FortifyEnchantingMgef);
    }

    private static string Suffix(INpcGetter npc) =>
        (npc.EditorID ?? npc.FormKey.ID.ToString("X8")).Replace(" ", "_");

    private static bool TryJewelryFallback(
        IPatcherState<ISkyrimMod, ISkyrimModGetter> state,
        Settings.Settings settings,
        INpcGetter boss,
        BossStrengthProfile profile,
        EnchantmentBuilder enchBuilder,
        ItemBuilder itemBuilder,
        OutfitPatcher outfitPatcher,
        DryRunReport report)
    {
        if (!settings.GearSelection.JewelryFallbackEnabled) return false;

        var (slot, baseKey) = settings.GearSelection.JewelryFallbackKind switch
        {
            JewelryFallbackKind.Amulet => (
                BipedObjectFlag.Amulet,
                settings.GearSelection.JewelryFallbackAmulet.IsNull
                    ? NamedUniqueAllowlist.FallbackAmulet
                    : settings.GearSelection.JewelryFallbackAmulet.FormKey),
            _ => (
                BipedObjectFlag.Ring,
                settings.GearSelection.JewelryFallbackRing.IsNull
                    ? NamedUniqueAllowlist.FallbackRing
                    : settings.GearSelection.JewelryFallbackRing.FormKey),
        };

        if (!state.LinkCache.TryResolve<IArmorGetter>(baseKey, out var baseArmor))
        {
            report.Skipped(boss, "jewelry fallback base not found");
            return true;
        }

        var pick = new SlotPick(slot, baseArmor, null);
        var primaryMag = MagnitudeFormula.ComputePrimary(profile, settings.MagnitudeScaling);

        if (settings.Output.DryRun)
        {
            report.Patched(boss, profile, pick, primaryMag);
            return true;
        }

        var ench = enchBuilder.Build(state, boss, profile, Suffix(boss));
        if (ench is null) { report.Skipped(boss, "no MGEF for top combat skill"); return true; }

        var item = itemBuilder.Build(state, boss, baseArmor, ench, profile, primaryMag);
        outfitPatcher.AddToInventory(state, boss, item);
        report.Patched(boss, profile, pick, primaryMag);

        if (settings.Output.VerboseLog)
            Console.WriteLine($"[BossGear] {boss.Name?.String ?? boss.EditorID} -> {profile.TopCombatSkill} {primaryMag:F1} (jewelry fallback)");

        return true;
    }
}
