using BossGearSynthesis.Analysis;
using BossGearSynthesis.BossDetection;
using BossGearSynthesis.Defaults;
using BossGearSynthesis.Enchantments;
using BossGearSynthesis.Gear;
using BossGearSynthesis.Logging;
using BossGearSynthesis.Outfit;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace BossGearSynthesis;

public class Program
{
    private static Lazy<Settings.Settings> _settings = null!;

    public static async Task<int> Main(string[] args)
    {
        return await SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings(
                nickname: "Settings",
                path: "settings.json",
                out _settings)
            .SetTypicalOpen(GameRelease.SkyrimSE, "BossGearSynthesis.esp")
            .Run(args);
    }

    public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        var settings = _settings.Value;
        SettingsDefaults.Apply(settings);

        var selector = new BossSelector(state, settings);
        var classifier = new TierClassifier(settings);
        var analyzer = new StrengthAnalyzer(settings, classifier);
        var effectMap = new EffectMap(settings.EffectMap);
        var enchBuilder = new EnchantmentBuilder(settings, effectMap);
        var slotResolver = new SlotResolver(settings);
        var matcher = new MaterialMatcher(settings);
        var itemBuilder = new ItemBuilder(settings);
        var outfitPatcher = new OutfitPatcher();
        var report = new DryRunReport();

        var matches = selector.Select().ToList();
        report.RecordRejections(selector.RejectedSamples, selector.RejectedCount);

        foreach (var match in matches)
        {
            var boss = match.Npc;
            var isUnique = selector.IsNamedUnique(boss);
            var profile = analyzer.Analyze(boss, isUnique, state);
            if (profile is null) { report.Skipped(match, "no skills resolved"); continue; }

            var pick = slotResolver.PickSlot(boss, state);
            if (pick is null) { report.Skipped(match, "no eligible outfit slot"); continue; }

            var baseArmor = matcher.Choose(pick.Item, pick.Slot, state);
            var primaryMag = MagnitudeFormula.ComputePrimary(profile, settings.MagnitudeScaling);
            var resolvedPick = pick with { Item = baseArmor };

            if (settings.Output.DryRun)
            {
                report.Patched(match, profile, resolvedPick, primaryMag);
                if (settings.Output.VerboseLog) LogMatch(match, profile, primaryMag);
                continue;
            }

            var ench = enchBuilder.Build(state, boss, profile, Suffix(boss));
            if (ench is null) { report.Skipped(match, "no MGEF for top combat skill"); continue; }

            var item = itemBuilder.Build(state, boss, baseArmor, ench, profile, primaryMag);
            outfitPatcher.Apply(state, boss, resolvedPick, item);
            report.Patched(match, profile, resolvedPick, primaryMag);

            if (settings.Output.VerboseLog) LogMatch(match, profile, primaryMag);
        }

        var reportPath = Path.Combine(state.DataFolderPath, settings.Output.ReportFileName);
        try { report.Write(reportPath); } catch { /* best effort */ }
    }

    private static void LogMatch(BossDetection.BossMatch match, BossStrengthProfile profile, float magnitude)
    {
        var name = match.Npc.Name?.String ?? match.Npc.EditorID;
        var plugin = match.Npc.FormKey.ModKey.FileName.String;
        var detail = string.IsNullOrEmpty(match.Detail) ? "" : $" [{match.Detail}]";
        Console.WriteLine($"[BossGear] {name} <{plugin}> via {match.Reason}{detail} -> {profile.TopCombatSkill} {magnitude:F1}");
    }

    private static string Suffix(INpcGetter npc) =>
        (npc.EditorID ?? npc.FormKey.ID.ToString("X8")).Replace(" ", "_");
}
